# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks

exclude: '^(ext/.*|.tox/)$'
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      #- id: check-toml
      #- id: check-json
      - id: check-yaml
        #exclude: '(conda/meta.yaml|.pep8speaks.yml)'

  - repo: https://github.com/PyCQA/doc8
    rev: v2.0.0
    hooks:
      - id: doc8
        args:
          - '--max-line-length=110'
          - '--ignore=D001'

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
        # exclude: ChangeLog\.rst$
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args: [--settings-path=setup.cfg]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
    - id: mypy
      args:
        - --follow-imports=normal
        - --install-types
        - --non-interactive
        #- --check-untyped-defs
      additional_dependencies:
        - "pyusb"
      files: ^cp210x.*\.py$

  - repo: https://github.com/myint/autoflake
    rev: v2.3.3
    hooks:
      - id: autoflake
        files: ^cp210x.*\.py$
        args:
          - --in-place
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/ambv/black
    rev: 26.3.1
    hooks:
      - id: black
        name: "Format code"
        language_version: python3
